<?php
    $URLS = array(
        'osu' => array('link' => 'http://oregonstate.edu/', 'text' => 'OSU Homepage', 'image' => 'osu.png', 'shortcut' => 'O'),
        'eecs' => array('link' => 'http://eecs.oregonstate.edu/', 'text' => 'EECS', 'image' => 'eecs.png', 'shortcut' => 'EE'),
        'library' => array('link' => 'http://library.oregonstate.edu/', 'text' => 'Library', 'image' => 'lib.png', 'shortcut' => 'LI'),
        'course' => array('link' => 'http://catalog.oregonstate.edu/', 'text' => 'Courses', 'image' => 'course.png', 'shortcut' => 'CU'),
        'piazza' => array('link' => 'https://piazza.com/', 'text' => 'Piazza', 'image' => 'piazza.png', 'shortcut' => 'PZ'),
        'grad' => array('link' => 'http://gradschool.oregonstate.edu/', 'text' => 'Graduate school', 'image' => 'grad.png', 'shortcut' => 'G'),
        'map' => array('link' => 'http://oregonstate.edu/campusmap/', 'text' => 'Map', 'image' => 'map.png', 'shortcut' => 'MA'),
        'mu' => array('link' => 'http://mu.oregonstate.edu/', 'text' => '', 'image' => 'mu.png', 'shortcut' => 'MU'),
        'success' => array('link' => 'http://success.oregonstate.edu/', 'text' => 'ASC', 'image' => 'asc.png', 'shortcut' => 'AS'),
        'homepage' => array('link' => 'http://people.oregonstate.edu/~shmarkas/', 'text' => 'My page', 'image' => 'home.png', 'shortcut' => 'HP'),
        'toastmasters' => array('link' => 'http://osutm.toastmastersclubs.org', 'text' => 'Toastmasters', 'image' => 'toastmasters.png', 'shortcut' => 'T'),
        'blog' => array('link' => 'http://blogs.oregonstate.edu/', 'text' => 'Blogs', 'image' => 'blog.png', 'shortcut' => 'BL'),
        'osl' => array('link' => 'http://osuosl.org/', 'text' => 'Open Source Lab', 'image' => 'osl.png', 'shortcut' => 'LA'),
        'myosu' => array('link' => 'http://myosu.oregonstate.edu/', 'text' => 'My OSU', 'image' => 'myosu.png', 'shortcut' => 'U'),
        'beaver' => array('link' => 'http://osubeaverstore.com/', 'text' => 'BeaverStore', 'image' => 'os.png', 'shortcut' => 'BS'),
        'sport' => array('link' => 'http://ourbeavernation.com/', 'text' => 'Sport', 'image' => 'beaver.png', 'shortcut' => 'S'),
        // 'tickets' => array('link' => 'http://beavertickets.com/', 'text' => 'Tickets', 'image' => 'beaver.png', 'shortcut' => 'T'),
        'health' => array('link' => 'http://studenthealth.oregonstate.edu/', 'text' => 'Health Center', 'image' => 'health.png', 'shortcut' => 'HC'),
        'helpdesk' => array('link' => 'http://eecs.oregonstate.edu/it/', 'text' => 'IT', 'image' => 'it.png', 'shortcut' => 'IT'),
        'webmail' => array('link' => 'https://webmail.oregonstate.edu/', 'text' => 'Webmail', 'image' => 'mail.png', 'shortcut' => 'WM'),
        'exmail' => array('link' => 'https://exmail.oregonstate.edu/', 'text' => 'EXmail', 'image' => 'exmail.png', 'shortcut' => 'X'),
        'digitalmeasures' => array('link' => 'https://www.digitalmeasures.com/login/oregonstate/faculty', 'text' => 'Digital Measures', 'image' => 'digitalmeasures.png', 'shortcut' => 'DM'),
        'calendar' => array('link' => 'http://calendar.oregonstate.edu/', 'text' => 'Calendar', 'image' => 'calendar.png', 'shortcut' => 'CA'),
        'adminfo' => array('link' => 'https://adminfo.ucsadm.oregonstate.edu/prod/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu', 'text' => 'Adminfo', 'image' => 'adminfo.png', 'shortcut' => 'AD'),
        'blackboard' => array('link' => 'https://my.oregonstate.edu', 'text' => 'Blackboard', 'image' => 'bb.png', 'shortcut' => 'BB'),
        'onid' => array('link' => 'http://onid.oregonstate.edu/', 'text' => 'ONID', 'image' => 'id.png', 'shortcut' => 'N'),
        'emp' => array('link' => 'http://osu.workforcehosting.com/', 'text' => 'EMP', 'image' => 'emp.png', 'shortcut' => 'EM'),
        'ecampus' => array('link' => 'http://ecampus.oregonstate.edu/', 'text' => 'E-campus', 'image' => 'ecampus.png', 'shortcut' => 'EC'),
        'connect' => array('link' => 'http://connect.oregonstate.edu/', 'text' => 'Connect', 'image' => 'connect.png', 'shortcut' => 'CN'),
        'alumni' => array('link' => 'https://securelb.imodules.com/s/359/start.aspx?sid=359', 'text' => 'Alumni', 'image' => 'alumni.png', 'shortcut' => 'AU'),
        'info' => array('link' => 'https://infosu.oregonstate.edu/', 'text' => 'InfOSU', 'image' => 'info.png', 'shortcut' => 'IO'),
    );
    $URLS_ = array(    
        'corvallis' => array('link' => 'http://www.corvallisoregon.gov/', 'text' => 'Corvallis', 'image' => 'corvallis.png', 'shortcut' => 'CO'),
        'visit' => array('link' => 'http://visitcorvallis.com/', 'text' => '', 'image' => 'visit.png', 'shortcut' => 'V'),
        'downtown' => array('link' => 'http://www.downtowncorvallis.org/', 'text' => '', 'image' => 'downtown.png', 'shortcut' => 'DT'),
        'artcenter' => array('link' => 'http://theartscenter.net/', 'text' => 'Arts center', 'image' => 'art.png', 'shortcut' => 'AR'),
        'white' => array('link' => 'http://whitesidetheatre.org/', 'text' => 'White side theatre', 'image' => 'white.png', 'shortcut' => 'WH'),
        'dark' => array('link' => 'http://darksidecinema.com/', 'text' => 'Dark side cinema', 'image' => 'dark.png', 'shortcut' => 'DS'),
        'majestic' => array('link' => 'http://www.majestic.org/', 'text' => 'theatre', 'image' => 'majestic.png', 'shortcut' => 'MJ'),
        'festival' => array('link' => 'http://corvallisfallfestival.org/', 'text' => 'Fall festival', 'image' => 'festival.png', 'shortcut' => 'F'),
        'live' => array('link' => 'http://www.corvallislive.com/', 'text' => 'Live', 'image' => 'live.png', 'shortcut' => 'LV'),
        'wine' => array('link' => 'http://heartofwillamette.com/', 'text' => 'Wineries', 'image' => 'wine.png', 'shortcut' => 'WI'),
        'bike' => array('link' => 'http://www.corvallisbikes.org/', 'text' => 'Bike co-op', 'image' => 'bike.png', 'shortcut' => 'BC'),
        'enterprise' => array('link' => 'http://www.enterprisecarshare.com/', 'text' => 'Car share', 'image' => 'enterprise.png', 'shortcut' => 'CS'),
        'hike' => array('link' => 'http://www.localhikes.com/', 'text' => 'Hiking', 'image' => 'hike.png', 'shortcut' => 'HI'),
        'piano' => array('link' => 'http://www.corvallispiano.org/', 'text' => 'Piano', 'image' => 'piano.png', 'shortcut' => 'PI'),
        'env' => array('link' => 'http://www.corvallisenvironmentalcenter.org/', 'text' => 'Environment', 'image' => 'env.png', 'shortcut' => 'EN'),
        'library' => array('link' => 'http://www.thebestlibrary.net/', 'text' => 'Public Library', 'image' => 'library.png', 'shortcut' => 'PL'),
        'craigslist' => array('link' => 'http://corvallis.craigslist.org', 'text' => 'Craigslist', 'image' => 'craigslist.png', 'shortcut' => 'CL'),
        'angellist' => array('link' => 'https://angel.co/corvallis', 'text' => 'AngelList', 'image' => 'angellist.png', 'shortcut' => 'AL'),
    )
?>
